OV2680_5987FHQ_SENSOR_LIBS_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_PATH := $(OV2680_5987FHQ_SENSOR_LIBS_PATH)
LOCAL_CFLAGS += -D_MSM_BEAR
LOCAL_CFLAGS += -DVFE_40
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../include

LOCAL_SRC_FILES:= ov2680_5987fhq_lib.c
LOCAL_MODULE           := libmmcamera_ov2680_5987fhq
LOCAL_SHARED_LIBRARIES := libcutils
LOCAL_MODULE_OWNER := qcom 
LOCAL_32_BIT_ONLY := true
LOCAL_PROPRIETARY_MODULE := true

include $(BUILD_SHARED_LIBRARY)
