OV8865_Q8V18A_SENSOR_LIBS_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_PATH := $(OV8865_Q8V18A_SENSOR_LIBS_PATH)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../include
LOCAL_CFLAGS += -D_MSM_BEAR
LOCAL_CFLAGS += -DVFE_40
LOCAL_SRC_FILES:= ov8865_q8v18a_lib.c

LOCAL_MODULE           := libmmcamera_ov8865_q8v18a
LOCAL_SHARED_LIBRARIES := libcutils

LOCAL_MODULE_OWNER := qcom
LOCAL_PROPRIETARY_MODULE := true

include $(BUILD_SHARED_LIBRARY)
